7) build docs only if docs directory is changed

diff --git a/docs/source/.readthedocs.yaml b/docs/source/.readthedocs.yaml
--- a/docs/source/.readthedocs.yaml
+++ b/docs/source/.readthedocs.yaml
@@ -15,6 +15,18 @@ build:
     # rust: "1.64"
     # golang: "1.19"
   jobs:
+    post_checkout:
+      # Cancel building pull requests when there aren't changed in the docs directory or YAML file.
+      # You can add any other files or directories that you'd like here as well,
+      # like your docs requirements file, or other files that will change your docs build.
+      #
+      # If there are no changes (git diff exits with 0) we force the command to return with 183.
+      # This is a special exit code on Read the Docs that will cancel the build immediately.
+      - |
+        if [ "$READTHEDOCS_VERSION_TYPE" = "external" ] && git diff --quiet origin/unknown_errors -- docs/;
+        then
+          exit 183;
+        fi
     pre_build:
       - echo "Command run at 'pre_build' step"
       - python -m pip install httpx==0.27.0 lxml==5.2.2
